version: '3.1'

services:
  db:
    container_name: hitech_db
    image: postgres:latest
    restart: always
    networks:
      - database
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    container_name: hitech_adminer
    image: adminer
    ports:
      - 8080:8080

  api:
    restart: always
    container_name: hitech_api
    build:
      context: .
    networks:
      - database
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma:/app/prisma
    env_file:
      - .env
    ports:
      - 3000:3000

networks:
  database:
